    
language: node_js
cache: yarn
node_js:
  - "11"
  - "10"
  - "8"
install: yarn
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test
    # - stage: deploy
    #   deploy:
    #   - provider: script
    #     skip_cleanup: true
    #     script: chmod +x ./scripts/deploy && ./scripts/deploy
    #     on:
    #       all_branches: true
